$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: custom_hahaha_model
endpoint_name: hahaha_edp
model: 
  path: ./custom_model/model/
code_configuration:
  code: ./custom_model/code/
  scoring_script: score.py
environment:
  conda_file: ./custom_model/environment/conda.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
compute: azureml:batch-cluster
resources:
  instance_count: 1
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: -1
logging_level: info