$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: hahaha-deployment-2
endpoint_name: hahahaedp
model: 
  path: ./custom_model/model/
code_configuration:
  code: ./custom_model/code/
  scoring_script: score.py
environment: azureml:xgbst_aml:1
compute: azureml:cpu-cluster
resources:
  instance_count: 1
max_concurrency_per_instance: 1
mini_batch_size: 2000
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: -1
logging_level: info